mv /home/jgrafton/autobuild/image/etc/DAEMON /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/FILESYSTEMS /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/LOGIN /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/NETWORKING /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/SERVERS /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/accounting /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/addswap /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/adjkerntz /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/apm /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/archdep /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/auditd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/auditdistd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/automount /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/automountd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/autounmountd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bgfsck /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/blacklistd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bluetooth /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bootparams /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bridge /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bsnmpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/bthidd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ccd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/cfumass /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/cleanvar /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/cleartmp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/cron /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ctld /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ddb /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/defaultroute /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/devd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/devfs /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/devmatch /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/dhclient /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/dmesg /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/dumpon /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/fsck /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ftp-proxy /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ftpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/gbde /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/geli /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/geli2 /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/gptboot /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/growfs /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/gssd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hastd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hcsecd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hostapd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hostid /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hostid_save /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/hostname /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/inetd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/iovctl /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ip6addrctl /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipfilter /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipfs /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipfw /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipfw_netflow /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipmon /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipnat /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ippool /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipropd_master /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipropd_slave /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ipsec /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/iscsictl /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/iscsid /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/jail /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kadmind /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kdc /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/keyserv /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kfd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kld /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kldxref /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/kpasswdd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ldconfig /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/linux /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/local /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/local_unbound /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/localpkg /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/lockd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/lpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mdconfig /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mdconfig2 /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mixer /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/motd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mountcritlocal /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mountcritremote /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mountd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/mountlate /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/moused /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/msgs /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/natd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/netif /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/netoptions /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/netwait /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/newsyslog /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nfscbd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nfsclient /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nfsd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nfsuserd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nisdomain /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nscd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/nsswitch /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ntpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ntpdate /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/opensm /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/os-release /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/othermta /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/pf /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/pflog /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/pfsync /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/power_profile /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/powerd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ppp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/pppoed /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/pwcheck /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/quota /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/random /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rarpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rctl /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/resolv /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rfcomm_pppd_server /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/root /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/route6d /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/routed /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/routing /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rpcbind /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rtadvd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rtsold /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/rwho /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/savecore /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sdpd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/securelevel /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sendmail /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/serial /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sppp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sshd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/statd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/static_arp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/static_ndp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/stf /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/swap /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/swaplate /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/syscons /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sysctl /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/syslogd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/sysvipc /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/tmp /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ubthidhci /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ugidfw /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/utx /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/var /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/virecover /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/watchdogd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/wpa_supplicant /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypbind /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypldap /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/yppasswdd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypserv /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypset /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypupdated /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/ypxfrd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/zfs /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/zfsbe /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/zfsd /home/jgrafton/autobuild/image/etc/rc.d/
mv /home/jgrafton/autobuild/image/etc/zvol /home/jgrafton/autobuild/image/etc/rc.d/
